config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('portfolio.urls')),
]

portfolio/urls.py
from django.urls import path
from . import views

app_name = 'portfolio'

urlpatterns = [
    path('home', views.home_page_view, name='home'),
]

portfolio/models.py
from django.db import models

# Create your models here.

portfolio/views.py
#  hello/views.py

from django.shortcuts import render


def home_page_view(request):
    return render(request, 'portfolio/home.html')


from django.shortcuts import render

# Create your views here.

portfolio/templates/portfolio/home.html
<!-- home.html -->

{% extends 'portfolio/layout.html' %}

{% block main %}
<h3>Titulo</h3>
<p>texto texto texto texto texto texto texto </p>

{% load static %}
<img src="{% static 'portfolio/images/30676_500x650.jpg' %}">
{% endblock %}

portfolio/templates/portfolio/layout.html
<!-- base.html -->
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>PW</title>

    {% load static %}
<link rel="stylesheet" href="{% static 'portfolio/css/style.css' %}">
</head>

<body>
<header>
    <div>
        Ana Weng
    </div>
    <nav>
        <a href="{% url 'portfolio:home' %}">Home</a>
        <a href="">products</a>
        <a href="">about</a>
        <a href="">contact</a>
    </nav>
</header>
<main>
    {% block main %}
    {% endblock main %}
</main>
<footer>
    <div>ULusófona, 2023</div>
</footer>
</body>